mixed-port: 7890
socks-port: 7891
allow-lan: true
bind-address: "*"
ipv6: true
mode: rule
log-level: silent
external-controller: '127.0.0.1:9090'

dns:

  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true

  default-nameserver:
   - 223.5.5.5
   - 223.6.6.6
   - 119.29.29.29
   - 180.76.76.76

   - 8.8.4.4
   - 8.8.8.8
   - 4.2.2.1
   - 4.2.2.2

  nameserver:
   - 223.5.5.5
   - 223.6.6.6
   - 119.29.29.29
   - 180.76.76.76

  fallback:
   - 8.8.4.4
   - 8.8.8.8
   - 4.2.2.1
   - 4.2.2.2

  fallback-filter:
    geoip: true

    ipcidr:
     - 240.0.0.0/4
     - 0.0.0.0/32

  #解决 快捷登录 只能扫码的问题
  fake-ip-filter:
   - 'localhost.sec.qq.com'
   - 'localhost.ptlogin2.qq.com'
   
   - 'localhost.work.weixin.qq.com'
   - 'localhost.weixin.qq.com'
   
   - 'localhost.pan.baidu.com'
